# Adapted from:
# https://github.com/luizdepra/hugo-coder/blob/main/docs/configurations.md#complete-example

title = "Jake Herrmann"
locale = 'en-us'
defaultcontentlanguage = "en"
theme = "hugo-coder"

# Cloudflare
[caches]
  [caches.images]
    dir = ':cacheDir/images'

# TODO: what is this?
[pagination]
pagerSize = 20

# Allows comments on blog posts?
# [services]
# [services.disqus]
# shortname = "yourdiscussshortname"

# TODO: what is this?
[markup.highlight]
style = "github-dark"

[params]
  author = "Jake Herrmann"

  # TODO: update
  # info = "Running scientific workflows at scale"
  # info = "Software Engineer"
  info = "Under construction, check back later! 👷"

  # TODO: where are these used?
  description = "Jake Herrmann's personal website"
  keywords = "blog,developer,personal"

  # TODO: use one of these
  # avatarurl = "images/avatar.jpg"
  # gravatar = "john.doe@example.com"

  # TODO: create these
  # faviconSVG = "/img/favicon.svg"
  # favicon_32 = "/img/favicon-32x32.png"
  # favicon_16 = "/img/favicon-16x16.png"

  # TODO: or 2025 when domain name was registered?
  since = 2026

  # TODO: what is this?
  enableTwemoji = true

  # TODO: auto selects dark mode?
  colorScheme = "auto"
  hidecolorschemetoggle = false

  # Filepaths are relative to the assets/ dir:
  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # TODO: use less obvious filename:
  # customJS = ["js/link-conversion.js"]

# TODO: what is this?
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# TODO:
# - add linkedin?
# - open links in new tab
#
# https://fontawesome.com/icons
# https://github.com/luizdepra/hugo-coder/blob/main/docs/configurations.md#social-icons-configuration
#
# Notes:
# - `name` becomes the `aria-label` attribute of the HTML element,
#   which is used for accessbility: https://fontawesome.com/v4/accessibility/
# - `fa-2x` refers to the icon size
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/jtherrmann"
# [[params.social]]
#   name = "Gitlab"
#   icon = "fa-brands fa-gitlab fa-2x"
#   weight = 1
#   url = "https://gitlab.com/johndoe/"
# TODO: use full-length key for obfuscation, don't include Email in the name here (insert it from the JS):
# [[params.social]]
#   name = "Email"
#   icon = "fa-solid fa-envelope fa-2x"
#   weight = 1
#   url = "4d41494c544f1a4a54484552524df50202c5d4fb01f5fd00c2f70301"
#   # Note on `rel` attribute:
#   # https://spencermortensen.com/articles/email-obfuscation/#link-conversion
#   # also recommends adding `noindex`, but I suspect that's not a valid value for `rel`, see:
#   # https://stackoverflow.com/a/55264065
#   # https://developers.google.com/search/docs/crawling-indexing/block-indexing
#   # https://www.w3schools.com/tags/att_a_rel.asp
#   rel = "nofollow"

# TODO: update these
# [[menu.main]]
#   name = "Blog"
#   weight = 1
#   url  = "posts/"
# [[menu.main]]
#   name = "About"
#   weight = 2
#   url = "about/"
