# Adapted from:
# https://github.com/luizdepra/hugo-coder/blob/main/docs/configurations.md#complete-example

title = "Jake Herrmann"
locale = 'en-us'
defaultcontentlanguage = "en"
theme = "hugo-coder"

# Cloudflare
[caches]
  [caches.images]
    dir = ':cacheDir/images'

# TODO: what is this?
[pagination]
pagerSize = 20

# Allows comments on blog posts?
# [services]
# [services.disqus]
# shortname = "yourdiscussshortname"

# TODO: what is this?
[markup.highlight]
style = "github-dark"

[params]
  author = "Jake Herrmann"

  # TODO: update
  # info = "Running scientific workflows at scale"
  info = "Software Engineer"
  # info = "Under construction, check back later! 👷"

  # TODO: where are these used?
  description = "Jake Herrmann's personal website"
  keywords = "blog,developer,personal"

  # TODO: use one of these
  # avatarurl = "images/avatar.jpg"
  # gravatar = "john.doe@example.com"

  # TODO: create these
  # faviconSVG = "/img/favicon.svg"
  # favicon_32 = "/img/favicon-32x32.png"
  # favicon_16 = "/img/favicon-16x16.png"

  since = 2026

  commit = "https://github.com/jtherrmann/jakeherrmann.com/tree/"

  # TODO: what is this?
  enableTwemoji = true

  # TODO: auto selects dark mode?
  colorScheme = "auto"
  hidecolorschemetoggle = false

  # Filepaths are relative to the assets/ dir:
  customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  customJS = ["js/custom.js"]

# TODO: what is this?
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# TODO:
# - add linkedin?
# - open links in new tab
#
# https://fontawesome.com/icons
# https://github.com/luizdepra/hugo-coder/blob/main/docs/configurations.md#social-icons-configuration
#
# Notes:
# - `name` becomes the `aria-label` attribute of the HTML element,
#   which is used for accessbility: https://fontawesome.com/v4/accessibility/
# - `fa-2x` refers to the icon size
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/jtherrmann"
# [[params.social]]
#   name = "Gitlab"
#   icon = "fa-brands fa-gitlab fa-2x"
#   weight = 1
#   url = "https://gitlab.com/johndoe/"
[[params.social]]
  name = "Email"
  icon = "fa-solid fa-envelope fa-2x"
  weight = 1
  url = "/contact/"

# [[menu.main]]
#   name = "Blog"
#   weight = 1
#   url  = "/posts/"
# [[menu.main]]
#   name = "About"
#   weight = 1
#   url = "/about/"
[[menu.main]]
name = "Contact"
weight = 1
url = "/contact/"
